name: customer_web
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.3.1
  google_fonts: ^2.3.1
  lottie: ^1.2.2
  responsive_framework: ^0.1.7
  rive: ^0.8.4
  transparent_image: ^2.0.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
